displayName=CAPS LOCK
author=TicTac7x
support=https://github.com/TicTac7x/runelite-plugins/tree/plugin-capslock
description=ALLOW WRITING MESSAGES IN CAPS LOCK
tags=caps,lock
plugins=tictac7x.capslock.TicTac7xCapsLockPlugin