package tictac7x.daily.ids;

import net.runelite.api.gameval.VarbitID;

public class VarbitId {
    public static final int VARROCK_ZAFF_BATTLESTAVES_COLLECTED = VarbitID.ZAFF_LAST_CLAIMED;
    public static final int VARROCK_DIARY_EASY_COMPLETE = VarbitID.VARROCK_DIARY_EASY_COMPLETE;
    public static final int VARROCK_DIARY_MEDIUM_COMPLETE = VarbitID.VARROCK_DIARY_MEDIUM_COMPLETE;
    public static final int VARROCK_DIARY_HARD_COMPLETE = VarbitID.VARROCK_DIARY_HARD_COMPLETE;
    public static final int VARROCK_DIARY_ELITE_COMPLETE = VarbitID.VARROCK_DIARY_ELITE_COMPLETE;

    public static final int KANDARIN_FLAX_COLLECTED = VarbitID.SEERS_FREE_FLAX;
    public static final int KANDARIN_DIARY_EASY_COMPLETE = VarbitID.KANDARIN_DIARY_EASY_COMPLETE;
    public static final int KANDARIN_DIARY_MEDIUM_COMPLETE = VarbitID.KANDARIN_DIARY_MEDIUM_COMPLETE;
    public static final int KANDARIN_DIARY_HARD_COMPLETE = VarbitID.KANDARIN_DIARY_HARD_COMPLETE;
    public static final int KANDARIN_DIARY_ELITE_COMPLETE = VarbitID.KANDARIN_DIARY_ELITE_COMPLETE;

    public static final int ACCOUNT_TYPE = VarbitID.IRONMAN;
    public static final int YANILLE_SAND_COLLECTED = VarbitID.YANILLE_SAND_CLAIMED;

    public static final int MORYTANIA_SLIME_COLLECTED = VarbitID.MORYTANIA_SLIME_CLAIMED;
    public static final int MORYTANIA_DIARY_EASY_COMPLETE = VarbitID.MORYTANIA_DIARY_EASY_COMPLETE;
    public static final int MORYTANIA_DIARY_MEDIUM_COMPLETE = VarbitID.MORYTANIA_DIARY_MEDIUM_COMPLETE;
    public static final int MORYTANIA_DIARY_HARD_COMPLETE = VarbitID.MORYTANIA_DIARY_HARD_COMPLETE;
    public static final int MORYTANIA_DIARY_ELITE_COMPLETE = VarbitID.MORYTANIA_DIARY_ELITE_COMPLETE;

    public static final int KOUREND_DIARY_EASY_COMPLETE = VarbitID.KOUREND_DIARY_EASY_COMPLETE;
    public static final int KOUREND_DIARY_MEDIUM_COMPLETE = VarbitID.KOUREND_DIARY_MEDIUM_COMPLETE;
    public static final int KOUREND_DIARY_HARD_COMPLETE = VarbitID.KOUREND_DIARY_HARD_COMPLETE;
    public static final int KOUREND_DIARY_ELITE_COMPLETE = VarbitID.KOUREND_DIARY_ELITE_COMPLETE;
    public static final int KOUREND_DYNAMITE_COLLECTED = VarbitID.KOUREND_FREE_DYNAMITE;

    public static final int LUMBRIDGE_DIARY_EASY_COMPLETE = VarbitID.LUMBRIDGE_DIARY_EASY_COMPLETE;
    public static final int LUMBRIDGE_DIARY_MEDIUM_COMPLETE = VarbitID.LUMBRIDGE_DIARY_MEDIUM_COMPLETE;
    public static final int LUMBRIDGE_DIARY_HARD_COMPLETE = VarbitID.LUMBRIDGE_DIARY_HARD_COMPLETE;
    public static final int LUMBRIDGE_DIARY_ELITE_COMPLETE = VarbitID.LUMBRIDGE_DIARY_ELITE_COMPLETE;
    public static final int EXPLORERS_RING_ALCHS_USED = VarbitID.LUMBRIDGE_FREE_ALCHS;

    public static final int NIGHTMAREZONE_HERB_BOXES_PURCHASED = VarbitID.NZONE_HERBBOXES_PURCHASED;

    public static final int IMPLING_JARS_PURCHASED = VarbitID.II_DAILY_JARS_PURCHASED;

    public static final int KINGDOM_OF_MISCELLANIA_FAVOR = VarbitID.MISC_APPROVAL;

    public static final int WESTERN_DIARY_EASY_COMPLETE = VarbitID.WESTERN_DIARY_EASY_COMPLETE;
    public static final int WESTERN_DIARY_MEDIUM_COMPLETE = VarbitID.WESTERN_DIARY_MEDIUM_COMPLETE;
    public static final int WESTERN_DIARY_HARD_COMPLETE = VarbitID.WESTERN_DIARY_HARD_COMPLETE;
    public static final int WESTERN_DIARY_ELITE_COMPLETE = VarbitID.WESTERN_DIARY_ELITE_COMPLETE;
    public static final int WESTERN_RANTZ_OGRE_ARROWS_COLLECTED = VarbitID.WESTERN_RANTZ_ARROWS;

    public static final int ARDOUGNE_DIARY_EASY_COMPLETE = VarbitID.ARDOUGNE_DIARY_EASY_COMPLETE;
    public static final int ARDOUGNE_DIARY_MEDIUM_COMPLETE = VarbitID.ARDOUGNE_DIARY_MEDIUM_COMPLETE;
    public static final int ARDOUGNE_DIARY_HARD_COMPLETE = VarbitID.ARDOUGNE_DIARY_HARD_COMPLETE;
    public static final int ARDOUGNE_DIARY_ELITE_COMPLETE = VarbitID.ARDOUGNE_DIARY_ELITE_COMPLETE;
    public static final int ARDOUGNE_PURE_ESSENCE_COLLECTED = VarbitID.ARDOUGNE_FREE_ESSENCE;

    public static final int WILDERNESS_DIARY_EASY_COMPLETE = VarbitID.WILDERNESS_DIARY_EASY_COMPLETE;
    public static final int WILDERNESS_DIARY_MEDIUM_COMPLETE = VarbitID.WILDERNESS_DIARY_MEDIUM_COMPLETE;
    public static final int WILDERNESS_DIARY_HARD_COMPLETE = VarbitID.WILDERNESS_DIARY_HARD_COMPLETE;
    public static final int WILDERNESS_DIARY_ELITE_COMPLETE = VarbitID.WILDERNESS_DIARY_ELITE_COMPLETE;
    public static final int WILDERNESS_LUNDAIL_RUNES_COLLECTED = VarbitID.LUNDAIL_LAST_CLAIMED;
}
